// Usage: npm run docs          write the generated documentation
//        npm run docs:check    fail if it is out of date (used by the tests)
//
// Generated from the component metadata, themes, recipes and variables, so it cannot drift from the code:
//   docs/components/<category>/<name>.md   one page per component
//   docs/components/README.md              index of every component
//   docs/themes.md, docs/recipes.md, docs/variables.md
//   README.md                              the compatibility table between <!-- components:start --> and <!-- components:end -->
// Hand-written guides (architecture, adding a component, ...) live next to them and are never touched.
const fs = require('fs');
const path = require('path');
const { ROOT } = require('./lib/paths');
const { loadRegistry } = require('./lib/registry');
const { NAMED_TYPES, normalize } = require('./lib/schema');
const { listThemes, loadThemeFile } = require('./lib/themes');
const { createBuilder } = require('./lib/recipes');
const { createVars } = require('./lib/variables');

const DOCS = path.join(ROOT, 'docs');
const GENERATED = '<!-- Generated by `npm run docs` from the component metadata. Do not edit by hand, edit the .meta.js file instead. -->';
const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');

function typeLabel(spec) {
  const raw = typeof spec === 'string' ? spec : spec.type;
  if (NAMED_TYPES[raw]) return raw;
  const s = normalize(spec);
  switch (s.type) {
    case 'enum': return `one of ${s.values.map((v) => `\`${v}\``).join(', ')}`;
    case 'list': return `list of ${typeLabel(s.of)}${s.min || s.max ? ` (${s.min || 0} to ${s.max || 'any'})` : ''}`;
    case 'object': return `object { ${Object.keys(s.fields).join(', ')} }`;
    case 'slot': return `components (${s.accepts || 'any'}-level)`;
    case 'image': return 'image { src, alt }';
    case 'cta': return 'cta { label, href }';
    default: return s.type;
  }
}

function fieldTable(fields) {
  const rows = Object.entries(fields).map(([k, spec]) => {
    const s = normalize(spec);
    return { k, s, spec };
  });
  const render = (list) => list.map(({ k, s, spec }) => `| \`${k}\` | ${cell(typeLabel(spec))} | ${s.default !== undefined ? `\`${cell(JSON.stringify(s.default))}\`` : ''} |`).join('\n');
  const required = rows.filter((r) => r.s.required);
  const optional = rows.filter((r) => !r.s.required);
  const head = '| Field | Type | Default |\n| --- | --- | --- |';
  return {
    required: required.length ? `${head}\n${render(required)}` : 'None.',
    optional: optional.length ? `${head}\n${render(optional)}` : 'None.',
  };
}

const RESPONSIVE_DOCS = {
  mobileLayout: (v) => `\`mobileLayout\`: ${v.map((x) => `\`${x}\``).join(', ')}. How columns arrange on phones (stack keeps order, reverse puts the last first, preserve keeps them side by side).`,
  mobileAlignment: (v) => `\`mobileAlignment\`: ${v.map((x) => `\`${x}\``).join(', ')}. Overrides text alignment below 480px (\`inherit\` keeps the desktop alignment). Best effort, images depend on the client.`,
  mobileColumns: (v) => `\`mobileColumns\`: ${v.map((x) => `\`${x}\``).join(', ')}. How many columns per row on phones.`,
  hideOnMobile: () => '`hideOnMobile`: hides it below 480px. Outlook desktop and Gmail on non-Google accounts ignore media queries and still show it.',
  hideOnDesktop: () => '`hideOnDesktop`: shows it only on phones. Clients that ignore media queries keep it hidden.',
};

function examples(entry) {
  const { data, settings } = entry.meta.previewData;
  const call = `[[ c('${entry.id}', ${JSON.stringify(data, null, 2)}${settings ? `, { settings: ${JSON.stringify(settings)} }` : ''}) ]]`;
  const node = JSON.stringify({ component: entry.id, data, ...(settings ? { settings } : {}) }, null, 2);
  const place = entry.meta.level === 'content'
    ? 'This is a content-level component: it goes inside a column, so put it in the `content` of a `layout/section` (or another layout).'
    : 'This is a section-level component: use it directly in an email body or a recipe.';
  return { call, node, place };
}

function componentPage(entry) {
  const m = entry.meta;
  const fields = fieldTable(m.fields);
  const settings = Object.entries(m.settings)
    .map(([k, spec]) => `| \`${k}\` | ${cell(typeLabel(spec))} | \`${cell(JSON.stringify(spec.default))}\` |`)
    .join('\n');
  const variants = Object.entries(m.variants).map(([k, v]) => `- **${k}**: ${v.description}${v.settings ? ` Sets ${Object.entries(v.settings).map(([sk, sv]) => `\`${sk}: ${sv}\``).join(', ')}.` : ''}`).join('\n');
  const responsive = m.responsive && Object.keys(m.responsive).length
    ? Object.entries(m.responsive).filter(([, v]) => v).map(([k, v]) => `- ${RESPONSIVE_DOCS[k](v)}`).join('\n')
    : 'No dedicated responsive settings. It follows the width of the column or section it sits in.';
  const ex = examples(entry);
  return `${GENERATED}
# ${m.name}

\`${entry.id}\` &middot; ${m.level}-level &middot; category: ${entry.category}

## Purpose

${m.description}

## Required fields

${fields.required}

## Optional fields

${fields.optional}

## Variants

Same data and structure, different styling. Pick one with \`{ variant: 'name' }\`.

${variants}

## Settings

Every setting has a default. Values may be token references (\`@colors.accent\`, \`@theme.card.radius\`). Pass overrides with \`{ settings: { ... } }\`.

| Setting | Type | Default |
| --- | --- | --- |
${settings}

## Responsive behavior

${responsive}

## Compatibility

| Outlook desktop | Gmail apps | Dark mode |
| --- | --- | --- |
| ${cell(m.compat.outlook)} | ${cell(m.compat.gmail)} | ${cell(m.compat.darkMode)} |

${(m.notes || []).map((n) => `- ${n}`).join('\n')}

## Example usage

${ex.place}

In an email (\`.mjml\`):

\`\`\`
${ex.call}
\`\`\`

As data (a node, for recipes and the remix API):

\`\`\`json
${ex.node}
\`\`\`
`;
}

function build() {
  const out = new Map();
  const registry = loadRegistry();

  for (const e of registry.all()) out.set(path.join('docs', 'components', e.category, `${e.name}.md`), componentPage(e));

  const index = [`${GENERATED}\n# Components\n\n${registry.all().length} components in ${registry.categories().length} categories. Each page lists its fields, variants, settings, responsive behavior and compatibility.\n`];
  for (const cat of registry.categories()) {
    index.push(`\n## ${cat}\n\n| Component | Level | Variants | Purpose |\n| --- | --- | --- | --- |`);
    for (const e of registry.all().filter((x) => x.category === cat)) {
      index.push(`| [${e.meta.name}](${cat}/${e.name}.md) | ${e.meta.level} | ${Object.keys(e.meta.variants).join(', ')} | ${cell(e.meta.description)} |`);
    }
  }
  out.set(path.join('docs', 'components', 'README.md'), index.join('\n') + '\n');

  const themes = listThemes().map((t) => ({ id: t, ...loadThemeFile(t) }));
  out.set(path.join('docs', 'themes.md'), `${GENERATED}
# Theme reference

Themes are style-only presets. They change type, spacing, radius, shadow, buttons, cards and which brand color roles are used, never colors, fonts or logos. See [Themes](themes-guide.md) for how they work and how to add one.

| Theme | Mood | Default variants and settings |
| --- | --- | --- |
${themes.map((t) => `| \`${t.id}\` | ${cell(t.description)} | ${Object.entries(t.components).map(([id, c]) => `\`${id}\`${c.variant ? ` &rarr; ${c.variant}` : ''}`).join(', ') || 'none'} |`).join('\n')}
`);

  const builder = createBuilder();
  const used = (nodes) => [...new Set(JSON.stringify(nodes).match(/"component":"([^"]+)"/g).map((m) => m.slice(13, -1)))];
  const recipeRows = [...builder.recipes].map(([id, r]) => {
    const nodes = builder.recipe(id, r.previewData);
    const top = Object.entries(r.fields).filter(([k]) => !['preheader', 'announcement', 'viewInBrowser', 'nav', 'footer'].includes(k))
      .map(([k, spec]) => `\`${k}\`${spec.required ? ' (required)' : ''}`).join(', ');
    return `### ${r.name}\n\n\`${id}\`${r.suggestedTheme ? ` &middot; suggested theme: \`${r.suggestedTheme}\`` : ''}\n\n${r.description}\n\n- Content it takes: ${top}. Every recipe also takes \`preheader\`, \`announcement\`, \`viewInBrowser\`, \`nav\` and \`footer\`.\n- Components used in the preview: ${used(nodes).map((c) => `\`${c}\``).join(', ')}\n`;
  });
  const sectionRows = [...builder.sections].map(([id, s]) => {
    const nodes = builder.section(id, s.previewData);
    return `- \`${id}\`: ${s.description} Uses ${used(nodes).map((c) => `\`${c}\``).join(', ')}.`;
  });
  out.set(path.join('docs', 'recipes.md'), `${GENERATED}
# Recipes and sections

A **section** is a reusable group of components. A **recipe** is a whole email built from sections and components. Both only produce data (nodes), so they can be remixed with another theme or variants. See [Recipes guide](recipes-guide.md) to write your own.

## Campaign recipes

Render one with \`npm run remix -- recipe <id> --theme <theme>\`, or in an email: \`[[ recipe('<id>', { ... }) ]]\`.

${recipeRows.join('\n')}
## Sections

Use one in a recipe with \`section('<id>', data)\`, or in an email with \`[[ recipeSection('<id>', { ... }) ]]\`.

${sectionRows.join('\n')}
`);

  const vars = createVars().list();
  out.set(path.join('docs', 'variables.md'), `${GENERATED}
# Variables

Semantic variable names mapped to Klaviyo template tags (\`variables/klaviyo.json\`). Use \`v('name')\` in an email or \`vars.get('name')\` in a recipe. **Verified** means the tag was checked against Klaviyo's help center. Event variables (cart and order) depend on your ecommerce integration: copy them exactly from the event preview in your Klaviyo account.

| Name | Klaviyo tag | Verified | Notes |
| --- | --- | --- | --- |
${vars.map((v) => `| \`${v.name}\` | \`${cell(v.tag)}\` | ${v.verified ? 'yes' : '**no**'} | ${cell(v.description)}${v.platformDependent ? ' Platform dependent.' : ''}${v.source ? ` [source](${v.source})` : ''} |`).join('\n')}
`);

  // README compatibility table
  const readmePath = path.join(ROOT, 'README.md');
  const readme = fs.readFileSync(readmePath, 'utf8');
  const table = [
    '| Component | Outlook desktop | Gmail apps | Dark mode |',
    '| --- | --- | --- | --- |',
    ...registry.all().map((e) => `| \`${e.id}\` | ${cell(e.meta.compat.outlook)} | ${cell(e.meta.compat.gmail)} | ${cell(e.meta.compat.darkMode)} |`),
  ].join('\n');
  const start = '<!-- components:start -->';
  const end = '<!-- components:end -->';
  const a = readme.indexOf(start);
  const b = readme.indexOf(end);
  if (a < 0 || b < 0) throw new Error('README.md needs the markers <!-- components:start --> and <!-- components:end -->');
  out.set('README.md', `${readme.slice(0, a + start.length)}\n${table}\n${readme.slice(b)}`);

  return out;
}

function main() {
  const check = process.argv.includes('--check');
  const files = build();
  const stale = [];

  for (const [rel, content] of files) {
    const abs = path.join(ROOT, rel);
    const current = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8').replace(/\r\n/g, '\n') : null;
    if (current !== content) stale.push(rel);
    if (!check && current !== content) {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content);
    }
  }

  // Generated component pages for components that no longer exist.
  const wanted = new Set([...files.keys()].map((f) => path.normalize(f)));
  const dir = path.join(DOCS, 'components');
  const orphans = [];
  const walk = (d) => {
    if (!fs.existsSync(d)) return;
    for (const f of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, f.name);
      if (f.isDirectory()) walk(p);
      else if (f.name.endsWith('.md') && !wanted.has(path.relative(ROOT, p))) orphans.push(path.relative(ROOT, p));
    }
  };
  walk(dir);

  if (check) {
    const problems = [...stale.map((s) => `out of date: ${s}`), ...orphans.map((o) => `no such component any more: ${o}`)];
    if (problems.length) {
      console.error(`Documentation is stale, run npm run docs:\n  ${problems.join('\n  ')}`);
      process.exit(1);
    }
    console.log(`Documentation is up to date (${files.size} files).`);
    return;
  }
  for (const o of orphans) fs.unlinkSync(path.join(ROOT, o));
  console.log(`Wrote ${stale.length} of ${files.size} generated files${orphans.length ? `, removed ${orphans.length} stale` : ''}.`);
}

main();
